- hosts: prometheus
  remote_user: slynko
  become: yes
  become_method: sudo
  roles:
    - prometheus

- hosts: grafana
  remote_user: slynko
  become: yes
  become_method: sudo
  roles:
    - grafana
    - node_exporter